name: fchat3-export
version: "1.0"
about: Reads F-Chat 3.0 client logs to stdout or HTML
author: Carlen White <whitersuburban@gmail.com>

settings:
  - ArgRequiredElseHelp

args:
  - files:
      help: What file(s) to read from
      short: f
      long: file
      multiple: true
      takes_value: true
      required: true
  - recursive:
      help: Recurse into directories
      short: r
      long: recurse
  - reverse:
      help: Reads files in reverse
      short: z
      long: reverse
  - html:
      help: generate HTML documents of inputted logs
      long: html
  - output:
      help: output for certain tasks
      long: output
      short: o
      takes_value: true